# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cur82j5f2O50XXsK5bhCF7KB1qlnBY6U
"""

# -*- coding: utf-8 -*-
"""
Aplicación Streamlit para la Predicción de Demanda de Transporte.

Esta aplicación carga un modelo de red neuronal entrenado con PyTorch para predecir el número de asientos vendidos
en un viaje.
"""
import streamlit as st
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import joblib
from pathlib import Path
from datetime import datetime

# --- MODELO ---
class DemandPredictionNet(nn.Module):
    def __init__(self, n_input_features):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(n_input_features, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 1)
        )

    def forward(self, x):
        return self.layers(x)

# --- CARGA DE MODELO Y PREPROCESADOR ---
@st.cache_resource
def load_model_and_preprocessor():
    model_path = Path(__file__).parents[1] / "models" / "modelo_pytorch1.pth"
    preproc_path = Path(__file__).parents[1] / "models" / "preprocesador1.pkl"

    if not model_path.exists() or not preproc_path.exists():
        st.error("❌ No se encontraron los archivos del modelo o preprocesador en la carpeta `models/`.")
        return None, None

    try:
        preprocessor = joblib.load(preproc_path)

        dummy_data = pd.DataFrame([[0, 0, 0, 0, 'Lugar_A', 'Lugar_B', 'bus', 'efectivo']],
                                  columns=['cupo_max', 'dia_semana', 'mes', 'hora',
                                           'origen', 'destino', 'tipo_carro', 'metodo_pago'])
        input_features = preprocessor.transform(dummy_data).shape[1]

        model = DemandPredictionNet(input_features)
        model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
        model.eval()

        return model, preprocessor
    except Exception as e:
        st.error(f"Error al cargar modelo o preprocesador: {e}")
        return None, None

# --- TÍTULO Y DESCRIPCIÓN ---
st.title("🚌 Predicción Inteligente de Demanda de Transporte")
st.markdown("""
Optimiza tus rutas prediciendo la demanda con nuestro modelo de red neuronal.
""")


# --- CARGA DE MODELO ---
model, preprocessor = load_model_and_preprocessor()
if model is None or preprocessor is None:
    st.stop()
else:
    st.success("✅ Modelo y preprocesador cargados.")

# --- FORMULARIO ---
with st.form("formulario_prediccion_demanda"):
    st.subheader("📋 Ingrese los Datos del Viaje")
    ciudades = ['Lugar_A', 'Lugar_B', 'Lugar_C', 'Lugar_D', 'Lugar_E']
    car_types = ['bus', 'minibus', 'van']
    metodos_pago = ['efectivo', 'transferencia', 'tarjeta de credito']

    col1, col2, col3 = st.columns(3)

    with col1:
        origen = st.selectbox("Origen", ciudades)
        destino = st.selectbox("Destino", ciudades)

    with col2:
        fecha_viaje = st.date_input("Fecha del viaje", value=datetime.now())
        if 'selected_time' not in st.session_state:
            st.session_state.selected_time = datetime.now().time()
        hora_viaje = st.time_input("Hora del viaje", value=st.session_state.selected_time)
        st.session_state.selected_time = hora_viaje

    with col3:
        tipo_carro = st.selectbox("Tipo de vehículo", car_types)
        cupo_max = st.number_input("Cupo máximo del vehículo", min_value=1, value=30, step=1)
        metodo_pago = st.selectbox("Método de pago principal", metodos_pago)

    enviado = st.form_submit_button("Predecir Demanda")

# --- PREDICCIÓN ---
if enviado:
    if origen == destino:
        st.error("⚠️ El origen y destino no pueden ser iguales.")
    else:
        dia_semana = fecha_viaje.weekday()
        mes = fecha_viaje.month
        hora = hora_viaje.hour

        columnas = ['cupo_max', 'dia_semana', 'mes', 'hora', 'origen', 'destino', 'tipo_carro', 'metodo_pago']
        input_data = pd.DataFrame([[cupo_max, dia_semana, mes, hora, origen, destino, tipo_carro, metodo_pago]], columns=columnas)

        try:
            input_processed = preprocessor.transform(input_data)
            input_tensor = torch.tensor(input_processed, dtype=torch.float32)
            with torch.no_grad():
                pred_cruda = model(input_tensor)
                pred = pred_cruda.item()

            pred_rounded = round(pred)
            asientos_final = min(max(0, pred_rounded), cupo_max)

            st.markdown("---")
            st.subheader("📈 Resultado de la Predicción")
            col1, col2 = st.columns(2)
            with col1:
                st.metric("Asientos a Vender (Estimado)", f"{asientos_final} asientos")
                ocupacion = (asientos_final / cupo_max) * 100
                st.metric("Ocupación Estimada", f"{ocupacion:.2f}%")
            with col2:
                st.progress(int(ocupacion))
                if ocupacion > 85:
                    st.success("¡Alta demanda esperada!")
                elif ocupacion > 50:
                    st.info("Demanda moderada.")
                else:
                    st.warning("Demanda baja.")

            with st.expander("Ver detalles técnicos"):
                st.dataframe(input_data)
                st.code(f"Predicción cruda: {pred:.4f}")
                st.code(f"Redondeada: {pred_rounded}")
                st.code(f"Ajustada a cupo: {asientos_final}")

        except Exception as e:
            st.error(f"Error durante la predicción: {e}")